### ISSUE TITLE
Compilation error after installing

### ISSUE THREAD

**Issue by Prashant-Kan** [salemdar/ngx-cookie#38] opened 2017-11-18 21:54 UTC
**I'm submitting/facing a query / bug ...**  
 Error
```ts
ERROR in Metadata version mismatch for module XXX/node_modules/ngx-cookie/index.d.ts, found version 4, expected 3, resolving symbol AppModule in XXX/src/app/app.module.ts, resolving symbol AppModule in XXX//src/app/app.module.ts, resolving symbol AppModule in XXX/src/app/app.module.ts
```
Its and compilation error. let me know what step is require to solve this. 

**Reproduction of the problem**
I have install the ngx-cookie using "npm install ngx-cookie --save" and then added CookieModule and CookieService to the respective files. Also, added the CookieModule.forRoot() in my app.module file. 
After all this step when i execute the npm start. It gives me given error. 

**Environment:**

* **ngx-cookie version:** 2.0.1

* **Angular version:** 2.x.x
 
* **Browser:** N/A

**Comment by salemdar** [comment] 2017-11-18 23:25
Can you try to clean your node modules / cache and perform a clean install please?

**Comment by Prashant-Kan** [comment] 2017-11-19 10:59
Yes, I tried but still getting the same error.

**Comment by Prashant-Kan** [comment] 2017-11-19 11:33
I tried uninstalling the latest version  of ngx-cookie and install the previous version It gets build successfully. Meanwhile continuing with the v1.0.1. 
That means it seems to be the issue for the latest version v2.0.1.  I would be using latest version untill get solution for that error.

**Comment by salarenko** [comment] 2017-11-20 15:08
I would like to report the same problem.
I've tried to reinstall node modules, but it didn't helped.
Whats interesting for me, when i run _ng serve_, first build fails throwing same error as mentioned in Prashant-Kan's post, but when i trigger ng serve change watcher to recompile, webpack compiles my project successfully.
Downgrading to v1.0.1 "solves" my problem by now.

**Comment by salemdar** [comment] 2017-11-20 15:23
@salarenko Are you on Angular v2.x as well?

**Comment by salarenko** [comment] 2017-11-20 15:45
@salemdar sorry, I've forgot to mention it.
I'm using Angular v4.3.5

**Comment by waiholiu** [comment] 2017-11-22 22:03
I can also vouch that this is happening for me too. 

Restoring to v1.0.1 fixes it but then this doesn't work in AOT

**Comment by salemdar** [comment] 2017-11-23 08:28
After some research, I have realised that it it caused by Angular v5. Could you guys confirm that the error goes away after upgrading to Angular v5?

**Comment by AsmaGargouri** [comment] 2017-11-29 11:14
Hi , I am having the same issue . 
I was using angular2-cookie and wanted to use ngx-cookie. 
And then I got this error : 
`ERROR in Error: Metadata version mismatch for module ..../node_modules/ngx-cookie/index.d.ts, found version 4, expected 3, resolving symbol AppModule in ..../src/app/app.module.ts, resolving symbol AppModule in ..../src/app/app.module.ts, resolving symbol AppModule in ...../src/app/app.module.ts
 `
I am using these versions : 

> Angular CLI: 1.5.4
Node: 8.9.1
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... tsc-wrapped

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.6.2
webpack: 3.8.1

**Any help would be appreciated**

**Comment by salemdar** [comment] 2017-11-30 08:08
@AsmaGargouri update to Angular v5 please.

**Comment by jdpnielsen** [comment] 2017-11-30 12:04
@salemdar Maybe you should add a comment to the readme, if you don't intend to support angular v4.

**Comment by salemdar** [comment] 2017-11-30 12:14
@jdpnielsen You are right, I will do that. You can always use older versions for <5.

**Comment by redent** [comment] 2018-04-18 08:37
What is the latest version supported for Angular 4?

**Comment by redent** [comment] 2018-04-18 08:41
Trial & Error says that the last version compatible with Angular 4 is 1.0.1

**Closed** 2018-11-01 14:11 UTC
