### ISSUE TITLE
angular4 universal CookieBackendService  Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by 916422** [salemdar/ngx-cookie#12] opened 2017-06-10 18:18 UTC
ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'headers' of undefined

**Comment by rimlin** [comment] 2017-07-19 10:02
+1

**Comment by Rafaelxpxpxp** [comment] 2017-08-21 05:54
+1

**Comment by salemdar** [comment] 2017-11-01 10:08
Should be fixed with the new version

**Closed by salemdar** 2017-11-01 10:08 UTC

**Comment by sinedsem** [comment] 2018-07-16 21:58
@salemdar are you sure this is fixed? I got same error in angular 6 (universal).

```
  protected set cookieString(val: string) {
    this.request.headers.cookie = val;
    this.response.headers.cookie = val; // in this line
  }
```

I've fixed it locally this way:

`        provide: 'RESPONSE', useValue: ({...{headers: {}}, res}) // fix for cookie service`

I use "ngx-cookie": "^4.0.2" and angular-universal starter https://github.com/enten/angular-universal

**Comment by stephenautomatik** [comment] 2018-08-31 02:03
@salemdar I am occasionally getting a similar error as well:

```
ERROR TypeError: Cannot read property 'headers' of undefined
    at CookieBackendService.set [as cookieString] (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:339970:27)
    at /Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:339893:31
    at CookieBackendService.CookieService.put (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:339754:29)
    at IntroComponent../src/app/main/intro/intro.component.ts.IntroComponent.endIntro (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:243511:28)
    at IntroComponent../src/app/main/intro/intro.component.ts.IntroComponent.ngOnInit (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:243455:18)
    at checkAndUpdateDirectiveInline (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:14025:19)
    at checkAndUpdateNodeInline (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15291:20)
    at checkAndUpdateNode (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15253:16)
    at prodCheckAndUpdateNode (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15797:5)
    at Object.updateDirectives (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:243339:353)
    at Object.updateDirectives (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15583:29)
    at checkAndUpdateView (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15235:14)
    at callViewAction (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15476:21)
    at execEmbeddedViewsAction (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15439:17)
    at checkAndUpdateView (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15236:5)
    at callViewAction (/Users/stephendickens/Desktop/Work/automatik/Website/automatik-website/dist/server.js:15476:21)
```

I'm not sure what triggers it because I can't reproduce the error every time I navigate to the page that throws it.

Using @angular ^6.0.2, @nguniversal ^6.0.0, and ngx-cookie ^4.0.2 with slightly modified server.ts file based on conversations in [https://github.com/salemdar/ngx-cookie/issues/51](url)
